build-qa:
  stage: build
  only:
    - qa
  tags:
    - qa-front 
  before_script:
    - cp -f /srv/project/envs/env-front-qa .env
  script:
    - docker-compose -f qa.docker-compose.yml build #--no-rm
test-qa:
  stage: test
  only:
    - qa
  tags:
    - qa-front 
  script:
    - docker run --rm project_front_front:latest yarn jest
    
deploy-qa:
  stage: deploy
  only:
    - qa
  tags:
    - qa-front
  script: 
    - docker-compose -f qa.docker-compose.yml up -d --force-recreate 
