version: "3"
networks:
  dev:
    external: true
services:
  front-dev:
    container_name: project-front-dev
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - 3100:3000
    environment:
      TZ: Europe/Moscow
    networks:
      - dev
    volumes:
      - /srv/project/public-uploads:/app/static/uploads
    entrypoint: npm run start
